global:
  scrape_interval: 15s

scrape_configs:
  - job_name: retailpulse-api
    static_configs:
      - targets: ["api:9000"]
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
