apiVersion: v1
kind: ConfigMap
metadata:
  name: retailpulse-config
data:
  APP_NAME: RetailPulse
  ENVIRONMENT: production
  REDIS_URL: redis://redis:6379/0
  MLFLOW_TRACKING_URI: http://mlflow:5000
